[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-scripts/fcitx.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'itchyny/lightline.vim'
